###
### PLUGINS
### 

source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload

plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option buffer softtabstop 4
    expandtab
} config %{
    hook global WinSetOption filetype=go noexpandtab
}

plug "Delapouite/kakoune-buffers" config %{
    map global user b ':enter-buffers-mode<ret>' -docstring 'Buffers'
}

plug "Delapouite/kakoune-cd" config %{
  map global user c ':enter-user-mode cd<ret>' -docstring 'Chdir'
}

plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
} 

###
### COLORS
###

colorscheme gruvy-light
# colorscheme gruvy-dark

###
### OPTIONS
###

set-option -add global ui_options ncurses_assistant=none
set-option -add global ui_options ncurses_status_on_top=false
set-option -add global ui_options ncurses_enable_mouse=false
set-option -add global ui_options terminal_set_title=false
set-option      global startup_info_version 20200901
set-option      global autoreload yes
set-option      global grepcmd 'rg -iHL --column'
set-option      global scrolloff 2,5
set-option      global autocomplete prompt
set-option      global tabstop 4
set-option      global indentwidth 4
set-option      global modelinefmt "{{mode_info}} {{context_info}} %opt{theme_modeline}"
set-option      global disabled_hooks '.*-(insert|indent)'
set-option      global idle_timeout 100
set-option      global completers word=buffer

###
### COMMANDS
###

alias global bd delete-buffer
alias global bd! delete-buffer!
alias global color colorscheme
alias global qa quit
alias global qa! quit!
alias global wqa write-quit
alias global wqa! write-quit!

define-command find -override -params 1 \
    -shell-script-candidates %{ rg --files } \
    %{ edit %arg{1} }

define-command source-kakrc -hidden -override \
    -docstring 'Source kakrc' \
    %{ source "%val{config}/kakrc" }

define-command source-current-file -hidden -override \
    -docstring 'Source current file' \
    %{ source %val{buffile} }

define-command reset-completions -override %{
    set-option window completers word=buffer
}

define-command toggle-highlighter -override -params .. %{
    try %{
        add-highlighter "window/%arg{@}" %arg{@}
        echo -markup {Information} %arg{@}
    } catch %{
        remove-highlighter "window/%arg{@}"
        echo -markup {Error} %arg{@}
    }
}

define-command toggle-wrap -override %{ 
    toggle-highlighter wrap -word -indent -marker '» ' 
}

define-command enable-wrap -override %{
    add-highlighter window/wrap wrap \
        -word -indent -marker '» '
}

define-command disable-wrap -override %{
    remove-highlighter window/wrap 
}

define-command window-padding -override %{
    declare-option line-specs padding_flags
    set-option window padding_flags %val{timestamp} '1| '
    try %{ remove-highlighter window/padding }
    add-highlighter window/padding flag-lines Default padding_flags
}

###
### HIGHLIGHTERS
###

add-highlighter -override global/show-whitespaces show-whitespaces \
    -tab '⍿' -tabpad ' ' -lf ' ' -spc ' ' -nbsp ' '

###
### HOOKS
###

hook global WinCreate .* %{ window-padding }

###
### MAPS
###

try %{ declare-user-mode toggle }

map global user   t ':enter-user-mode toggle<ret>' -docstring 'Toggle'
map global toggle w ':toggle-wrap<ret>'            -docstring 'Wrap'

try %{ declare-user-mode reload }

map global user   r ':enter-user-mode reload<ret>' -docstring 'Reload'
map global reload f ':source-current-file<ret>'    -docstring 'Current file'
map global reload c ':source-kakrc<ret>'           -docstring 'kakrc'

try %{ declare-user-mode find }

map global user f   ':enter-user-mode find<ret>'   -docstring 'Find'
map global find f   ':find '                       -docstring 'File'
map global find b   ':buffer '                     -docstring 'Buffer'

map global user l   ':enter-user-mode lsp<ret>'    -docstring 'LSP mode'

map global normal '%' '<c-s>%'
map global normal '{' '[p;k'
map global normal '}' ']p;'
map global normal '#' :comment-line<ret>

map global normal ^ q
map global normal <a-^> Q
map global normal q b
map global normal Q B  
map global normal <a-q> <a-b>
map global normal <a-Q> <a-B>

###
### FILETYPES
###

hook global WinSetOption filetype=.* %{
    expandtab

    set-option buffer tabstop 4
    set-option buffer indentwidth 4
    set-option buffer softtabstop 4
}

hook global WinSetOption filetype=go %{
    set-option window indentwidth 0 
    set-option window lsp_auto_highlight_references true
    set-option window formatcmd goimports

    hook window BufWritePre .* %{ lsp-formatting-sync }

    lsp-enable-window
    lsp-diagnostic-lines-disable window
    lsp-inline-diagnostics-disable window
    
    remove-highlighter shared/go
    source "%val{config}/rc/highlight/go.kak"
}
